version: 0.2

phases:
  install:
    runtime-versions:
      java: correctto8
    build:
      commands:
        - echo Build started on `date`
        - mvn test
    post-build:
      commands:
        - echo Build completed on `date`
        - mvn package
artifacts:
  files:
    - target/*.war
  discard-paths: yes